apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: y6qkez9sb-python
  janus-idp.io/tekton: y6qkez9sb-python
  backstage.io/kubernetes-id: y6qkez9sb-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: y6qkez9sb-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
